// English template
export const en = {
    login: "Login",
    new_post: "Write New Blog",
    etda_blog: "ETDA Blogs",
    home: "Home",
    message_board: "Message Board",
    community_board: "Community Board",
    my_board: "My Board",
    activity: "Activity",
    manage_blogs: "Manage Blogs",
    join_event: "Join event",
    unjoin_event: "Unjoin event",
    edit_event: "Edit event",
    delete_event: "Delete event",
    follow_blog: "Follow Blog",
    unfollow_blog: "Un follow blog",
    edit_blog: "Edit Blog",
    delete_blog: "Delete Blog",
    comment_here: "Comment here",
    send: "Send",
    search: "Search",
    done: "Done",
    reply: "Reply",
    search_by_tags: "Search by tags",
    comments: "comments",
    report: "Report",
    select_topic_for_report: "Select topic for report",
    fake_news: "Fake news",
    cyber_bully: "Cyber bully",
    threat: "Threat",
    report_reason: "Give reason for report this post not suitable",
    enter_reason: "Enter your reason...",
    event_topic: "Event topic",
    event_schedule: "Event schedule",
    add_event_date: "Add event date",
    change: "Change",
    create: "Create",
    start_event: "Start event",
    work_shop: "Work shop",
    add_schedule: "Add schedule",
    edit_event: "Edit Event",
    notifications: "Notifications",
    event_today: "Your events today",
    see_upcomming_events: "See upcomming events",
    minutes_ago: "minutes ago",
    day_ago: "day ago",
    month_ago: "month ago",
    create_blog: "Create blog",
    post: "Post",
    enter_topic: "Enter your topic here...",
    enter_post_detail: "Enter your post here...",
    pick_picture: "Pick picture",
    tag: "Tag",
    search_tags: "Search tags",
    or: "Or",
    poll: "Poll",
    poll_topic: "Poll Topic",
    poll_detail: "Poll detail",
    for_student: "For student",
    for_general: "For general",
    survey: "Survey",
    create_new_event: "Create New Event",
    my_events: "My events",
    all_events: "All events",
    detail: "Detail",
    create_new_poll: "Create new poll",
    create_new_survey: "Create new survey",
    survey_topic: "Survey topic",
    survey_detail: "Survey detail",
    select_all: "Select all",
    un_select_all: "Un select all",
    wait_for_publish: "Wait for publish",
    publish: "Publish",
    reject: "Reject",
    cancle: "Cancle",
    blog_selected: "Blog selected",
    my_profile: "My Profile",
    setting: "Setting",
    edit_profile: "Edit Profile",
    logout: "Logout",
    contact_me: "Contact me",
    professional: "Professional",
    organization: "Organization",
    position: "Position",
    type_of_user: "Type of user",
    language: "Language",
    password: "Password",
    enter_password: "Enter your password...",
    change_password: "Change password",
    delete_account: "Delete account",
    current_password: "Current password",
    new_password: "New password",
    enter_new_password: "Enter new password",
    confirm_new_password: "Confirm new password",
    confirm_your_password: "Confirm your password",
    save: "Save",
    confirm: "Confirm",
    continue: "Continue",
    name: "Name",
    read_only: "Read Only",
    post_and_read: "Post and Read",
    change_type_of_account: "Change type of your account",
    edit_profile_footer: "* If you want to change permission to post. You can request to admin.",
    delete_account_title: "Delete your account permanently!",
    delete_account_detail: "Your data cannot be recovered if you reactivate your account in the future.",
    delete_account_detail2: "If you want to delete. Please enter your password for confirm delete your account.",
    change_user_type_title: "Change permission to posts and read",
    change_user_type_detail: "Please, enter your reason for change permission to posts and read.",
    change_user_type_detail2: "Please, enter your experience or workmanship that will help make decision for ETDA. (Give 3 experience or less than)",
    enter_reason: "Enter your reason...",
    enter_experience: "Enter your experience...",
    sucess_change_role: "Your registration has been submitted, to post please wait for administrator approval.",
    date: "Date",
    time: "Time",
    post_to_etda: "Post to ETDA feed",
    enter_event_schedule: "Enter your event schedule here...",
    poll_topic_here: "Enter your topic poll here",
    poll_question: "Poll question",
    type_of_poll: "Type of Poll",
    poll_question_here: "Poll answer here",
    add_answer: "Add answer",
    create_poll: "Create Poll",
    survey_topic_here: "Enter your topic survey here",
    survey_question: "Survey question",
    survey_question_here: "Enter your question here",
    survey_answer_here: "Enter your answer here",
    add_new_question: "Add new question",
    event: "Event",
    schedule: "Schedule",
    edit: "Edit",
    create_event: "สร้างกิจกรรม"
}