platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_frameworks!

target 'LOOKs' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
  
  # pod 'FBSDKLoginKit'
  pod 'GoogleSignIn', '~> 5.0.2'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'RNLine', :path => '../node_modules/@xmartlabs/react-native-line'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  target 'LOOKsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'LOOKs-tvOS' do
  # Pods for ETDA_Mobile-tvOS

  target 'LOOKs-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
