- name: Mirroring Repository

  uses: pixta-dev/repository-mirroring-action@v1
  with:
    # SSH private key for ssh connection to the target repository
    ssh_private_key: ${{ secrets.SSH_PRIVK }} # optional
    # Target url
    target_repo_url: "https://gitlab.com/etda-it-dev/dev-mobileapp/etda-mobile.git"
    # Username for ssh connection
    ssh_username:  # optional, default is git
