name: Mirror Gitlab

on: [ push ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: iamapinan/git-mirror-action@v1.0.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVK }}
        with:
          source-repo: 'git@github.com:techcraft-code/ETDA-Mobile.git'
          destination-repo: 'git@gitlab.com:etda-it-dev/dev-mobileapp/etda-mobile.git'
          destination-branch: 'main'
